sudo: false

language: php

php:
# - 7.1
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql

#matrix:
#  allow_failures:
#    - php: 7.4snapshot

before_install:
  - composer self-update
  - cp composer.json.dist composer.json

install:
  - composer require xoops/base-requires:dev-master
  - composer update

before_script:
  - mysql -e 'create database xoops_test;'
  - php console/console.php ci-bootstrap
  - php console/console.php ci-install
  - php console/console.php install-module avatars
  - php console/console.php install-module page

script:
  - xoops_lib/vendor/bin/phpunit
  - wget https://github.com/diff-sniffer/git/releases/download/0.3.2/git-phpcs.phar
  - php git-phpcs.phar $TRAVIS_COMMIT_RANGE

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.4snapshot" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.4snapshot" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
